apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: 496278789073.ecr.ap-northeast-2.amazonaws.com/skccuser17-book:latest
          ports:
            - containerPort: 8080